# Configuracion especifica para Entorno LOCAL (tu máquina)
# Por defecto se activa si no dices nada, o con SPRING_PROFILES_ACTIVE=local

# Base de datos PostgreSQL para desarrollo local (Lee del .env)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/migraine_tracker}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driverClassName=org.postgresql.Driver

# Conservar esquema sin borrar datos de PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Evitamos que se ejecute el data.sql con sintaxis Postgres
spring.sql.init.mode=never

# Seguridad - Permitir cliente Vite Local
cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
